/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:05a5ac57-f534-4f4c-b34f-a889b0f05d2d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Ubi7Ypk9W",
    "aws_user_pools_web_client_id": "29kppljorqs89kpo3bmfv84qq7",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS"
};


export default awsmobile;
