/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4ef475b6-1d72-41a3-8528-585bf4a7298a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8q1Us58Wn",
    "aws_user_pools_web_client_id": "4rfukfbpbe8of0lara1o4it4h5",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS", //COGNITO_USER_POOLS  COGNITO_IDENTITY_POOLS
    "aws_cloud_logic_custom": [
        {
            "name": "cloudApp",
            "endpoint": "https://n032q4ru98.execute-api.us-east-1.amazonaws.com/release",
            "region": "us-east-1"
        }
    ] 
};


export default awsmobile;
